### ISSUE TITLE
Jaeger's client configuration not being fetched from environment variables

### ISSUE THREAD

**Issue by bitbanshee** [topfreegames/eventsgateway#13]
Problem: Unable to configure Jaeger's Client through environment variables, leading to shenanigans to deploy Events Gateway properly like setting a proxy Pod to forward traces to a cluster wide, centralized Jaeger Agent instead of reporting traces to a common sidecar deployment fashion.

Proposed fix: Remove (or at least stop using) [dependency](https://github.com/topfreegames/eventsgateway/blob/fa7340c42e14a51eaa600a114a49f9f07c9f4be6/go.mod#L22) on https://github.com/topfreegames/eventsgateway/extensions `jaeger/config.go` which is unnecessary and limiting, and configure the Jaeger's Client using only environment variables. Using only Jaeger's Client available environment variables for configuration is better than prefixing and, this, limiting its configuration possibilities.

Replace:
https://github.com/topfreegames/eventsgateway/blob/fa7340c42e14a51eaa600a114a49f9f07c9f4be6/app/app.go#L109-L117

By:
```go
// (...)
// inside `import`
        "github.com/uber/jaeger-client-go"
	"github.com/uber/jaeger-client-go/config"
	opentracing "github.com/opentracing/opentracing-go"
// (...)

func (a *App) configureJaeger() error {
        cfg, err := config.FromEnv()
        if err != nil {
                a.log.Error("Could not get Jaeger's Client configuration from environment. Disabling it.", err)
                return err
        }
        tracer, closer, err := cfg.NewTracer()
	if err != nil {
		return err
	}
        opentracing.SetGlobalTracer(tracer)
	return nil
}
```

**Comment by manuellysuzik** [comment]
Hello @bitbanshee ! Thank you very much. I applied the change to the server [here](https://github.com/topfreegames/eventsgateway/pull/14/commits/c5aa0d4586a834e3313c3b417ccf2920d8cfc124).  The jaeger configuration is not necessary anymore since it will be replaced by OpenTelemetry Exporter 😄
